### ISSUE TITLE
Model renames should exclude DataList methods like find()

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-upgrader#17] opened 2016-09-07 04:59 UTC
``` diff
-        $hasTestMembers = Member::get()->find('Email', 'hayley@test.com');
+        $hasTestMembers = Member::get()->find('SilverStripe\\Control\\Email\\Email', 'hayley@test.com');
```

``` diff
-            new TextField('Email', 'Email'),
+            new TextField('SilverStripe\\Control\\Email\\Email', 'SilverStripe\\Control\\Email\\Email'),
```

**Comment by dhensby** [comment] 2018-06-29 21:17
duplicate of #23 (I know this is newer, but 23 has more information)

**Closed by dhensby** 2018-06-29 21:17 UTC
