### ISSUE TITLE
RebuildDev class not found

### ISSUE THREAD

**Issue by chtombleson** [silverstripe/silverstripe-upgrader#164] opened 2019-04-09 01:15 UTC
This pull request: https://github.com/silverstripe/silverstripe-upgrader/pull/159 adds RebuildDev, this class is not in the code base.

Running an `upgrade-code all --namespace="App\\Bob" --psr4` gives the following error:

```
PHP Fatal error:  Uncaught Error: Class 'SilverStripe\Upgrader\Composer\Rules\RebuildDev' not found in /home/chris/.config/composer/vendor/silverstripe/upgrader/src/Console/RecomposeCommand.php:167
Stack trace:
#0 /home/chris/.config/composer/vendor/symfony/console/Command/Command.php(255): SilverStripe\Upgrader\Console\RecomposeCommand->execute(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#1 /home/chris/.config/composer/vendor/silverstripe/upgrader/src/Console/AutomatedCommandTrait.php(51): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /home/chris/.config/composer/vendor/silverstripe/upgrader/src/Util/CommandRunner.php(50): SilverStripe\Upgrader\Console\RecomposeCommand->automatedRun(Array, Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /home/chris/.config/composer/vendor/silverstripe/upgrader/src/Console/AllInOneCommand.php(140): SilverStrip in /home/chris/.config/composer/vendor/silverstripe/upgrader/src/Console/RecomposeCommand.php on line 167
```

# Pull request
* [x] https://github.com/silverstripe/silverstripe-upgrader/pull/173

**Comment by kinglozzer** [comment] 2019-04-09 08:50
Looks like a regression from https://github.com/silverstripe/silverstripe-upgrader/commit/c4c62bbc038ae2ff5b584d6fb9c77c0a1ca3e216

**Comment by kinglozzer** [comment] 2019-04-09 09:44
cc @maxime-rainville

**Comment by maxime-rainville** [comment] 2019-04-11 22:12
:scream: Did an emergency fix here to unstuck people https://github.com/silverstripe/silverstripe-upgrader/pull/167

Looks like I must have forgotten to do a `git add` before my commit and somehow it managed to get through peer review.

I'll need to do a follow up PR to rewrite that RebuildDev class. I don't think I still have a copy around.

I'll add some quick smoke test that actually tries to call the upgrader to make sure basic stuff actually works.

**Comment by maxime-rainville** [comment] 2019-04-11 22:45
[Release 1.4.1 is out](https://github.com/silverstripe/silverstripe-upgrader/releases/tag/1.4.1)

**Comment by robbieaverill** [comment] 2019-04-17 22:57
I think the 1.4.1 releases fixes this critical bug, so I'm going to close it. The follow up can be treated separately, or we can reopen this issue and lower the triage level

**Comment by maxime-rainville** [comment] 2019-05-01 07:31
We still need to re-implement the missing class.

**Comment by chillu** [comment] 2019-06-11 21:50
Don't forget to create an upgrader release after this is merged

**Closed** 2019-06-12 03:02 UTC
Labels: affects/v4, change/patch, effort/easy, impact/critical, type/bug
