### ISSUE TITLE
Correct private static references

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-upgrader#74] opened 2018-05-13 23:10 UTC
# Overview

A common thing I've found in projects I've been upgrading is that `$db` etc are referred to as public statics. Although unorthodox in SS3, it silently worked. In SS4 it causes warnings.

It should be feasible to rewrite a common whitelist of static properties to private statics. Those from DataObjects, Controllers, and ModelAdmins seem the most common.

# Acceptance Criteria

 * Devs can opt into this through a specific upgrader task (or flag)
 * Rewrites ALL private statics (to keep implementation simple)
 * Approach is well documented in upgrading guide

# Notes

 * Bonus points: Limit to implementors of `Configurable` (incl. subclasses of those implementors). Timeboxed to 4h

# Out of Scope

 * Opt-out per declaration via `@ internal`
 * Opt-in per declaration via `@ config`

# Pull Requests
- [ ] ~https://github.com/silverstripe/silverstripe-framework/pull/8643~
- [ ] ~https://github.com/silverstripe/silverstripe-upgrader/pull/144~
- [x] https://github.com/silverstripe/silverstripe-upgrader/pull/146
- [x] https://github.com/silverstripe/silverstripe-framework/pull/8699

**Comment by chillu** [comment] 2018-07-08 22:16
I've confirmed that those warnings surface on dev/build, at least for the . Hence I'm downgrading this from `impact/high` to `impact/medium`, because there's a pretty obvious way to fix it after running the upgrader.

![image.png](https://images.zenhubusercontent.com/52b2f46cf0808b12020000f7/de786fdb-8fd6-4681-9434-e140f4060449)

**Comment by sminnee** [comment] 2018-07-08 22:56
Okay, but this is a pretty tedious part of upgrades... can it be “extra medium”? ;-)

**Comment by chillu** [comment] 2018-07-08 23:52
We've been recommending `private static` for many years, I don't think this is widespread?

**Comment by sminnee** [comment] 2018-07-09 01:20
Maybe I drew the short straw, but it was present on each of the 2 or 3 projects the I found.

If anyone else has seen common use of non-private statics in their sites, maybe post here?

**Comment by robbieaverill** [comment] 2018-07-09 01:41
I've come across public statics a few times, or statics without a visibility (public by default). I think I'm with @chillu in that it's less common now though and there's a clear way to see and fix them already.

Unless they're tagged with `@config` PHPDocs it'd be a little dangerous to auto-rewrite public statics to private statics.

**Comment by maxime-rainville** [comment] 2018-07-10 06:10
Part of what makes this one difficult is that we don't have a nice elegant way of saying this _this attribute/method that use to be `public` should now be `private`_. A similar constraint is in play in #18.

If we had a way to define visibility updates in `.upgrade.yml` this would be easy to fix.

**Comment by dhensby** [comment] 2018-07-10 10:32
I'd say that it's a pretty safe assumption that `public static`s in SS code should be `private static` now. I think that'd be right about 90% of the time. It's a lot easier to provide this functionality, and for a dev to then use `git add -p` to only accept the changes that were right and discard the others than it is to go through and manually upgrade all of them.

**Comment by TomasVotruba** [comment] 2018-07-29 11:06
I'm starting to looking into feature that could Rector handle based #128

Do you any code snippet for this feature showing the before/after?

```diff
-$someService::$staticProperty;
+$someService::$privateProperty;
```

**Comment by dhensby** [comment] 2018-07-29 16:00
It's basically:

```diff

class Page extends SiteTree {
-    public static $db = array(
+    private static $db = array(
        ...
    );
}
```

**Comment by maxime-rainville** [comment] 2019-01-16 01:57
Everything's been merged.

**Closed by maxime-rainville** 2019-01-16 01:57 UTC
Labels: affects/v4, change/minor, effort/medium, impact/medium, type/bug
